php:
    image: php:7.0-fpm
    volumes:
        - ./public:/var/www/html

web:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - "./public:/var/www/html"
    - "./conf/app.conf:/etc/nginx/conf.d/default.conf"
  links:
    - php  
